name: my_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0+1
  image_picker: ^1.0.4
  http: ^0.13.6
  connectivity_plus: ^5.0.2
  dash_chat_2: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/background.jpg
    - assets/images/Background2.jpg
    - assets/images/path1.png
    - assets/images/rice.jpg
  
  fonts:
    - family: LufgaSemiBold
      fonts:
        - asset: assets/fonts/LufgaSemiBold.ttf

